### ISSUE TITLE
%.1f crashes for doubles with no decimal places (eg 1.0)

### ISSUE THREAD

**Issue by rockgecko-development** [Naddiseo/dart-sprintf#15]
The following input:
```
double n = 1;
sprintf("%.1f", n);
```

throws:

RangeError (index): Invalid value: Not in range 0..1, inclusive: 2

dart:core                                                                                                                     List.[]
c:%5Cflutter%5C.pub-cache%5Chosted%5Cpub.dartlang.org%5Csprintf-4.0.0%5Clib%5Csrc%5Cformatters%5Cfloat_formatter.dart 271:18  FloatFormatter._round
c:%5Cflutter%5C.pub-cache%5Chosted%5Cpub.dartlang.org%5Csprintf-4.0.0%5Clib%5Csrc%5Cformatters%5Cfloat_formatter.dart 195:5   FloatFormatter.asFixed
c:%5Cflutter%5C.pub-cache%5Chosted%5Cpub.dartlang.org%5Csprintf-4.0.0%5Clib%5Csrc%5Cformatters%5Cfloat_formatter.dart 139:15  FloatFormatter.asString
c:%5Cflutter%5C.pub-cache%5Chosted%5Cpub.dartlang.org%5Csprintf-4.0.0%5Clib%5Csrc%5Csprintf_impl.dart 85:55                   PrintFormat.call

`%.2f` works tho.

**Comment by Naddiseo** [comment]
Looks like my last fix didn't actually fix it, I'll keep looking

**Comment by rockgecko-development** [comment]
Wow that was quick. Thanks a lot!
