### ISSUE TITLE
Positional argument interpretation is off by one

### ISSUE THREAD

**Issue by dalewking** [Naddiseo/dart-sprintf#22]
sprintf supports positional arguments as in:

    %1$s-%2$s

to specify which argument is used where the numbers start from 1. You do support those in the format, but the problem is that such a format will currently fail because your interpretation of the numbers is off by one. You are expecting such a positional argument to start at 0 not 1. So to make it work currently I have to use:

    %0$s-%1$s

**Comment by Naddiseo** [comment]
It's seems I've completely forgot about positions arguments; I never tested for them.

I will have a look into this

**Comment by dalewking** [comment]
Your code supports them and the relevant code is here: https://github.com/Naddiseo/dart-sprintf/blob/master/lib/src/sprintf_impl.dart#L61 

That code should be more like:

      var _arg = _parameter == null ? null : args[int.parse(_parameter) - 1];
