### ISSUE TITLE
Why did you take class approach?

### ISSUE THREAD

**Issue by wirekang** [Naddiseo/dart-sprintf#29]
I'm just curious. You could define just a function, but defined **class PrintFormat.** Why?

**Comment by Naddiseo** [comment]
I didn't know dart when I wrote the library (it had only been announced a few months prior) so there wasn't a lot of idiomatic code to look at for inspiration. At the time I was using a lot of OOP design to solve things, and so it transferred over to dart. I also didn't know the scoping rules very well, so classes allowed me to encapsulate internal state without haven't to worry about access. I'd probably solve it differently if I were to rewrite it.

**Comment by wirekang** [comment]
Thank you very much for a kind explanation!
