### ISSUE TITLE
Is it possible to specify the order of arguments in the formatter?

### ISSUE THREAD

**Issue by blamath20** [Naddiseo/dart-sprintf#31]
In one language, I need sprintf('%s %s', ['a', 'b']), to be printed as 'a b' but in another language I need it to print 'b a'.
Is there any way to specify which %s should be satisfied with which argument? Something like:

sprintf('%s1 %s2', ['a', 'b']), 
sprintf('%s2 %s1', ['a', 'b']),

**Comment by Naddiseo** [comment]
Yes, I believe you use the `$` flag: `sprintf('%2$s %1$s', ['a', 'b']);`. There's an example usage [in the tests](https://github.com/Naddiseo/dart-sprintf/blob/master/test/sprintf_test.dart#L166)
