### ISSUE TITLE
warning when compiling with dartdevc

### ISSUE THREAD

**Issue by robertmuth** [Naddiseo/dart-sprintf#8]
[warning] Unsafe implicit cast from '(dynamic, dynamic) → dynamic' to '(dynamic, dynamic) → Formatter'. This usually indicates that type information was lost and resulted in 'dynamic' and/or a place that will have a failure at runtime. (package:sprintf/src/sprintf_impl.dart, line 102, col 35)

**Comment by Naddiseo** [comment]
PR welcome.

**Comment by Naddiseo** [comment]
@robertmuth, was this fixed in PR #11 ?
