### ISSUE TITLE
Rounding is buggy

### ISSUE THREAD

**Issue by paresy** [Naddiseo/dart-sprintf#9]
Test-Case:
print(sprintf("|%.2f|", [2.09846]));

Expected result:
|2.10|

Actual result:
|2.00|

**Comment by paresy** [comment]
Ping :) 

Can i assist in solving the issue? Can you give me a hint what is going wrong?

**Comment by Naddiseo** [comment]
@paresy, Hi, it's crunch time at $work at the moment, I haven't had time to look into this. If you want to give it a shot, I think it's probably an issue with [the rounding function](https://github.com/Naddiseo/dart-sprintf/blob/master/lib/src/formatters/float_formatter.dart#L265-L285), maybe an off-by-one error.

**Comment by paresy** [comment]
Thanks a lot!
